# region Positioning

SCHEDULE_MIN_COL = 6
SCHEDULE_MIN_ROW = 12
SCHEDULE_BOTTOM_OFFSET = 2

SCHEDULE_GROUP_WIDTH = 5
SCHEDULE_JUNK_COLUMNS = 1
SCHEDULE_PERIOD_HEIGHT = 2

SCHEDULE_GROUP_NAME_ROW = 10
SCHEDULE_WEEKDAY_COL = 1
SCHEDULE_SUBGROUP_ROW = 11
SCHEDULE_NUMBER_COL = 2

SUBSTITUTIONS_MIN_ROW = 6
SUBSTITUTIONS_MIN_COL = 2
SUBSTITUTIONS_MAX_COL = 11

SUBSTITUTION_WIDTH = 4

# endregion

# region Data

SCHEDULE_DEFAULT_SUBGROUP = 0
SCHEDULE_WEEKDAY_BORDER = "medium"

# endregion
