SCHEDULE_DATA_GROUP_ROW = 10
SCHEDULE_DATA_ODD_COLOR = "FFFFFF00"
SCHEDULE_DATA_NO_SUBGROUP = 0
SCHEDULE_DATA_NUMBER_COLUMN = 2
SCHEDULE_DATA_SUBGROUP_ROW = 11
SCHEDULE_DATA_WEEKDAY_COLUMN = 1

SCHEDULE_FOOTER_OFFSET = -2
SCHEDULE_GROUP_WIDTH = 5
SCHEDULE_HEADER_INDEX = 11
SCHEDULE_JUNK_OFFSET = -1
SCHEDULE_PERIOD_HEIGHT = 2
SCHEDULE_SIDEBAR_WIDTH = 4

SUBSTITUTIONS_HEADER_INDEX = 5
SUBSTITUTIONS_WIDTH = 10
